INSERT INTO materia (id,nombre) VALUES
	(1,'Afluentes, Efluentes y Desechos'),
	(2,'Aislamiento II'),
	(3,'Aislamiento III'),
    (4,'algebra Lineal'),
	(5,'algebra y Geometria Analitica'),
	(6,'Algoritmos'),
	(7,'Algoritmos de Programacion'),
	(8,'Algoritmos en Bioinformatica'),
	(9,'Aislamiento I'),
	(10,'Analisis en Variable Compleja'),
	(11,'Analisis Estatico de Programas y Herramientas Asociadas'),
	(12,'Analisis General de Alimentos'),
	(13,'Analisis Matematico'),
	(14,'Analisis Matematico I'),
	(15,'Analisis Matematico II'),
	(16,'Analisis Matematico II "A"'),
	(17,'Analisis Matematico III'),
	(18,'Analisis Matematico IV'),
	(19,'Anatomia y Fisiologia'),
	(20,'Arquitectura de Computadoras'),
	(21,'Arquitectura de Software I'),
	(22,'Arquitectura de Software II'),
	(23,'Arquitectura Naval I'),
	(24,'Arquitectura Naval II'),
	(25,'Arquitectura Naval III'),
	(26,'Asuntos Legales'),
	(27,'Bases de Datos'),
	(28,'Bases de Datos de Macromoleculas'),
	(29,'Bases de Datos II'),
	(30,'Bases de la Microbiologia Aplicada'),
	(31,'Biocatalisis'),
	(32,'Biocatalizadores en la industria'),
	(33,'Biodepuraciones y Biorremediacion'),
	(34,'Biofisica'),
	(35,'Bioinformatica'),
	(36,'Bioinformatica II'),
	(37,'Bioinformatica III'),
	(38,'Bioinformatica IV'),
	(39,'Biologia Celular y Molecular'),
	(40,'Biologia de Alimentos'),
	(41,'Biologia de Sistemas'),
	(42,'Biologia del Desarrollo'),
	(43,'Biologia General'),
	(44,'Biologia Molecular y Celular'),
	(45,'Bioprocesos I'),
	(46,'Bioprocesos II'),
	(47,'Bioquimica'),
	(48,'Bioquimica Celular y Molecular'),
	(49,'Bioquimica de Proteinas'),
	(50,'Bioquimica I'),
	(51,'Bioquimica II'),
	(52,'Biorremediacion'),
	(53,'Biotecnologia Clasica y Moderna'),
	(54,'Biotecnologia de Hongos'),
	(55,'Biotecnologia Vegetal'),
	(56,'Bromatologia'),
	(57,'Buenas Practicas de Laboratoria'),
	(58,'Buenas Practicas en la Produccion Farmaceutica'),
	(59,'Calculo Avanzado'),
	(60,'Caracteristicas de Lenguajes de Programacion'),
	(61,'Comunicaciones I'),
	(62,'Comunicaciones II'),
	(63,'Construccion de Interfaces de Usuario'),
	(64,'Construccion Naval I'),
	(65,'Construccion Naval II'),
	(66,'Control Automatico I'),
	(67,'Control Automatico II'),
	(68,'Control de Procesos'),
	(69,'Control de Robots'),
	(70,'Control Digital y Estocastico'),
	(71,'Control Robusto'),
	(72,'Curso Complementario'),
	(73,'Derechos de Autor y Derechos de Copia en la Era Digital'),
	(74,'Desarrollo de Aplicaciones'),
	(75,'Dibujo Naval'),
	(76,'Diseño Asistido'),
	(77,'Diseño asistido II'),
	(78,'Diseño Asistido III'),
	(79,'Diseño basado en Microcontroladores'),
	(80,'Diseño de Cruceros I'),
	(81,'Diseño de cruceros II'),
	(82,'Diseño de Veleros I'),
	(83,'Diseño de Veleros II'),
	(84,'Diseño estadistico de experimentos'),
	(85,'Ecologia'),
	(86,'Economia'),
	(87,'Ecotoxicologia y Quimica Ambiental'),
	(88,'Electronica I'),
	(89,'Electronica II'),
	(90,'Electronica Industrial'),
	(91,'Electrotecnia General'),
	(92,'Electrotecnia Naval'),
	(93,'Elementos de Fisica'),
	(94,'Elementos de Higiene y Seguridad'),
	(95,'Elementos de Ingenieria de Software'),
	(96,'Elementos de programacion y logica'),
	(97,'Emergencias y Primeros Auxilios'),
	(98,'Emprendedorismo'),
	(99,'Ergonomia y diseño de interiores'),
	(100,'Estabilidad I'),
	(101,'Estabilidad II'),
	(102,'Estadistica Aplicada'),
	(103,'Estadistica Avanzada'),
	(104,'Estadistica para Tecnicos'),
	(105,'Estrategias de Persistencia'),
	(106,'Estructuras de Datos'),
	(107,'etica profesional'),
	(108,'etica y Legislacion'),
	(109,'etica y Legislacion Alimentaria'),
	(110,'Evaluacion Ambiental'),
	(111,'Evaluacion de Riesgos'),
	(112,'Evaluacion Sensorial'),
	(113,'Facturacion y Ventas'),
	(114,'Farmacologia'),
	(115,'Fenomenos de Transporte'),
	(116,'Fisica Aplicada'),
	(117,'Fisica I'),
	(118,'Fisica II'),
	(119,'Fisica III'),
	(120,'Fisicoquimica'),
	(121,'Fisiologia General'),
	(122,'Fisiologia Humana'),
	(123,'Fisiologia Vegetal'),
	(124,'Fisiologia y Genetica de Bacterias'),
	(125,'Formulacion y Evaluacion de Bioproyectos'),
	(126,'Formulacion y Evaluacion de Proyectos'),
	(127,'Fundamentos de Inmunologia'),
	(128,'Fundamentos de Programacion'),
	(129,'Fundamentos en Biologia Celular y Molecular'),
	(130,'Genetica Molecular'),
	(131,'Genomica Funcional'),
	(132,'Geologia del Petroleo'),
	(133,'Geometria Descriptiva'),
	(134,'Gestion Ambiental'),
	(135,'Gestion de Calidad'),
	(136,'Gestion de Calidad e Inocuidad'),
	(137,'Gestion de Costos'),
	(138,'Gestion de las Organizaciones'),
	(139,'Gestion de Proyectos de Software'),
	(140,'Herramientas Declarativas en Programacion'),
	(141,'Higiene y Seguridad Industrial'),
	(142,'Identificacion y Control Adaptativo'),
	(143,'Incendios y Explosiones'),
	(144,'Informatica'),
	(145,'Informatica, Algoritmos y Programacion'),
	(146,'Ingenieria Ambiental'),
	(147,'Ingenieria de Requerimientos'),
	(148,'Ingenieria Genetica I'),
	(149,'Ingenieria Genetica II'),
	(150,'Ingles'),
	(151,'Ingles Basico'),
	(152,'Ingles I'),
	(153,'Ingles II'),
	(154,'Ingles Tecnico'),
	(155,'Inmunologia'),
	(156,'Instrumentacion'),
	(157,'Instrumentos y Mediciones'),
	(158,'Introduccion a  Ingenieria en Automatizacion y Control Industrial'),
	(159,'Introduccion a la Bioinformatica'),
	(160,'Introduccion a la Biotecnologia'),
	(161,'Introduccion a la Biotecnologia Animal'),
	(162,'Introduccion a la Biotecnologia Vegetal'),
	(163,'Introduccion a la Ingenieria en Alimentos'),
	(164,'Introduccion a la Nautica'),
	(165,'Introduccion a la programacion'),
	(166,'Introduccion a la Programacion'),
	(167,'Introduccion a las Arquitecturas de Software'),
	(168,'Introduccion al Conocimiento de la Fisica y la Quimica'),
	(169,'Introduccion al Desarrollo de Videojuegos'),
	(170,'Laboratorio de Analisis Bromatologico'),
	(171,'Laboratorio de Automatizacion I'),
	(172,'Laboratorio de Automatizacion II'),
	(173,'Laboratorio de Control de Calidad'),
	(174,'Laboratorio de Microbiologia'),
	(175,'Laboratorio de Quimica Instrumental'),
	(176,'Laboratorio de Sistemas Operativos y Redes'),
	(177,'Lectura y Escritura Academica'),
	(178,'Legislacion Ambiental'),
	(179,'Lenguajes Formales y Automatas'),
	(180,'Logica y Programacion'),
	(181,'Maquinas Industriales'),
	(182,'Matematica'),
	(183,'Matematica Aplicada'),
	(184,'Matematica Avanzada'),
	(185,'Matematica I'),
	(186,'Matematica II'),
	(187,'Matematica III'),
	(188,'Materiales'),
	(189,'Materiales compuestos'),
	(190,'Materias Primas de la Industria Petroquimica'),
	(191,'Mecanica de Fluidos'),
	(192,'Mecanica de los Fluidos Aplicada'),
	(193,'Medio Ambiente y Quimica Ambiental'),
	(194,'Metodologia de Desarrollo de Sistemas en Hardware y Software'),
	(195,'Metodos Numericos'),
	(196,'Microbiologia Aplicada'),
	(197,'Microbiologia de Alimentos'),
	(198,'Microbiologia General'),
	(199,'Microbiologia Industrial'),
	(200,'Modelizacion de Sistemas Biologicos'),
	(201,'Modelos Animales y Bioterio'),
	(202,'Nanobiotecnologia '),
	(203,'Operaciones Unitarias'),
	(204,'Organizacion de Computadoras'),
	(205,'Organizacion de la Produccion Naval'),
	(206,'Organizacion Industrial'),
	(207,'Organizacion y Arquitectura de Computadores'),
	(208,'Parseo y generacion de codigo'),
	(209,'Participacion y Gestion en Proyectos de Software Libre'),
	(210,'Politicas Publicas en la Sociedad de la Informacion y la Era Digital'),
	(211,'Practica del Desarrollo de Software'),
	(212,'Practica Profesional Supervisada'),
	(213,'Preservacion de Alimentos'),
	(214,'Probabilidad y Estadistica'),
	(215,'Problemas Actuales de Ciencia y Tecnologia'),
	(216,'Procesamiento Digital de Imagenes'),
	(217,'Procesos Industriales'),
	(218,'Produccion de Proteinas Recombinantes'),
	(219,'Produccion por Fermentadores'),
	(220,'Programacion con Objetos I'),
	(221,'Programacion con Objetos II'),
	(222,'Programacion con Objetos III'),
	(223,'Programacion Concurrente'),
	(224,'Programacion Funcional'),
	(225,'Quimica Analitica'),
	(226,'Quimica Biologica'),
	(227,'Quimica de los Alimentos'),
	(228,'Quimica General'),
	(229,'Quimica I'),
	(230,'Quimica II'),
	(231,'Quimica Organica'),
	(232,'Quimica Organica Ecocompatible'),
	(233,'Quimica Organica I'),
	(234,'Quimica Organica II'),
	(235,'Recuperacion y Purificacion de Proteinas'),
	(236,'Recursos Humanos'),
	(237,'Redes de Computadoras'),
	(238,'Reservorios Petroleros'),
	(239,'Riesgos I'),
	(240,'Riesgos II'),
	(241,'Salud Publica y Ambiente'),
	(242,'Seguridad de la Informacion'),
	(243,'Seguridad en Industrias  y Empresas'),
	(244,'Seguridad industrial'),
	(245,'Semantica de Lenguajes de Programacion'),
	(246,'Seminario de Automatizacion y Control'),
	(247,'Seminario de Grado'),
	(248,'Seminarios'),
	(249,'Seminarios sobre Herramientas o Tecnicas Puntuales'),
	(250,'Señales y Sistemas'),
	(251,'Servicios de Planta'),
	(252,'Servicios y Operaciones de Planta'),
	(253,'Sistemas de Gestion de la Salud y la Seguridad Ocupacional'),
	(254,'Sistemas de Informacion Geografica'),
	(255,'Sistemas de Representacion'),
	(256,'Sistemas Distribuidos'),
	(257,'Sistemas Embebidos de Aplicacion Industrial'),
	(258,'Sistemas No Lineales'),
	(259,'Sistemas Operativos'),
	(260,'Sistemas Propulsivos'),
	(261,'Taller de Arquitectura Naval'),
	(262,'Taller de Dibujo y Maqueteria'),
	(263,'Taller de Fisica Aplicada'),
	(264,'Taller de Quimica'),
	(265,'Taller de Trabajo Intelectual'),
	(266,'Taller de Trabajo Universitario'),
	(267,'Tecnicas Analiticas Instrumentales'),
	(268,'Tecnicas Analiticas Separativas'),
	(269,'Tecnicas Avanzadas de Programacion'),
	(270,'Tecnicas Basicas de Laboratorio'),
	(271,'Tecnicas de Biologia Molecular y Genetica'),
	(272,'Tecnicas Digitales "A"'),
	(273,'Tecnicas Inmunologicas'),
	(274,'Tecnicas numericas de analisis de estructuras'),
	(275,'Tecnicatura y mercado laboral'),
	(276,'Tecnologia de Alimentos'),
	(277,'Teoria de Circuitos'),
	(278,'Teoria de la Computacion'),
	(279,'Termodinamica'),
	(280,'Topicos de Confiabilidad y Mantenimiento para la Industria Automatizada'),
	(281,'Topicos de Control Avanzado'),
	(282,'Topicos de Inteligencia Artificial'),
	(283,'Toxicologia de Alimentos'),
	(284,'Trabajo de Insercion Profesional'),
	(285,'Trabajo Final'),
	(286,'Tratamiento de Efluentes'),
	(287,'Tratamiento de Efluentes Solidos y Gaseosos'),
	(288,'Virologia Aplicada'),
	(289,'Vision Artificial');
