INSERT INTO cpi_unqbot.materia (id,nombre) VALUES
	(1,'Afluentes, Efluentes y Desechos'),
	(2,'Aislamiento II'),
	(3,'Aislamiento III'),
    (4,'Álgebra Lineal'),
	(5,'Álgebra y Geometría Analítica'),
	(6,'Algoritmos'),
	(7,'Algoritmos de Programación'),
	(8,'Algoritmos en Bioinformática'),
	(9,'Aislamiento I'),
	(10,'Análisis en Variable Compleja'),
	(11,'Análisis Estático de Programas y Herramientas Asociadas'),
	(12,'Análisis General de Alimentos'),
	(13,'Análisis Matemático'),
	(14,'Análisis Matemático I'),
	(15,'Análisis Matemático II'),
	(16,'Análisis Matemático II "A"'),
	(17,'Análisis Matemático III'),
	(18,'Análisis Matemático IV'),
	(19,'Anatomía y Fisiología'),
	(20,'Arquitectura de Computadoras'),
	(21,'Arquitectura de Software I'),
	(22,'Arquitectura de Software II'),
	(23,'Arquitectura Naval I'),
	(24,'Arquitectura Naval II'),
	(25,'Arquitectura Naval III'),
	(26,'Asuntos Legales'),
	(27,'Bases de Datos'),
	(28,'Bases de Datos de Macromoléculas'),
	(29,'Bases de Datos II'),
	(30,'Bases de la Microbiología Aplicada'),
	(31,'Biocatálisis'),
	(32,'Biocatalizadores en la industria'),
	(33,'Biodepuraciones y Biorremediación'),
	(34,'Biofísica'),
	(35,'Bioinformática'),
	(36,'Bioinformática II'),
	(37,'Bioinformática III'),
	(38,'Bioinformática IV'),
	(39,'Biología Celular y Molecular'),
	(40,'Biología de Alimentos'),
	(41,'Biología de Sistemas'),
	(42,'Biología del Desarrollo'),
	(43,'Biología General'),
	(44,'Biología Molecular y Celular'),
	(45,'Bioprocesos I'),
	(46,'Bioprocesos II'),
	(47,'Bioquímica'),
	(48,'Bioquímica Celular y Molecular'),
	(49,'Bioquímica de Proteínas'),
	(50,'Bioquímica I'),
	(51,'Bioquímica II'),
	(52,'Biorremediación'),
	(53,'Biotecnología Clásica y Moderna'),
	(54,'Biotecnología de Hongos'),
	(55,'Biotecnología Vegetal'),
	(56,'Bromatología'),
	(57,'Buenas Prácticas de Laboratoria'),
	(58,'Buenas Prácticas en la Producción Farmacéutica'),
	(59,'Cálculo Avanzado'),
	(60,'Características de Lenguajes de Programación'),
	(61,'Comunicaciones I'),
	(62,'Comunicaciones II'),
	(63,'Construcción de Interfaces de Usuario'),
	(64,'Construcción Naval I'),
	(65,'Construcción Naval II'),
	(66,'Control Automático I'),
	(67,'Control Automático II'),
	(68,'Control de Procesos'),
	(69,'Control de Robots'),
	(70,'Control Digital y Estocástico'),
	(71,'Control Robusto'),
	(72,'Curso Complementario'),
	(73,'Derechos de Autor y Derechos de Copia en la Era Digital'),
	(74,'Desarrollo de Aplicaciones'),
	(75,'Dibujo Naval'),
	(76,'Diseño Asistido'),
	(77,'Diseño asistido II'),
	(78,'Diseño Asistido III'),
	(79,'Diseño basado en Microcontroladores'),
	(80,'Diseño de Cruceros I'),
	(81,'Diseño de cruceros II'),
	(82,'Diseño de Veleros I'),
	(83,'Diseño de Veleros II'),
	(84,'Diseño estadístico de experimentos'),
	(85,'Ecología'),
	(86,'Economía'),
	(87,'Ecotoxicología y Química Ambiental'),
	(88,'Electrónica I'),
	(89,'Electrónica II'),
	(90,'Electrónica Industrial'),
	(91,'Electrotecnia General'),
	(92,'Electrotecnia Naval'),
	(93,'Elementos de Física'),
	(94,'Elementos de Higiene y Seguridad'),
	(95,'Elementos de Ingeniería de Software'),
	(96,'Elementos de programación y lógica'),
	(97,'Emergencias y Primeros Auxilios'),
	(98,'Emprendedorismo'),
	(99,'Ergonomía y diseño de interiores'),
	(100,'Estabilidad I'),
	(101,'Estabilidad II'),
	(102,'Estadística Aplicada'),
	(103,'Estadística Avanzada'),
	(104,'Estadística para Técnicos'),
	(105,'Estrategias de Persistencia'),
	(106,'Estructuras de Datos'),
	(107,'Ética profesional'),
	(108,'Ética y Legislación'),
	(109,'Ética y Legislación Alimentaria'),
	(110,'Evaluación Ambiental'),
	(111,'Evaluación de Riesgos'),
	(112,'Evaluación Sensorial'),
	(113,'Facturación y Ventas'),
	(114,'Farmacología'),
	(115,'Fenómenos de Transporte'),
	(116,'Física Aplicada'),
	(117,'Física I'),
	(118,'Física II'),
	(119,'Física III'),
	(120,'Fisicoquímica'),
	(121,'Fisiología General'),
	(122,'Fisiología Humana'),
	(123,'Fisiología Vegetal'),
	(124,'Fisiología y Genética de Bacterias'),
	(125,'Formulación y Evaluación de Bioproyectos'),
	(126,'Formulación y Evaluación de Proyectos'),
	(127,'Fundamentos de Inmunología'),
	(128,'Fundamentos de Programación'),
	(129,'Fundamentos en Biología Celular y Molecular'),
	(130,'Genética Molecular'),
	(131,'Genómica Funcional'),
	(132,'Geología del Petróleo'),
	(133,'Geometría Descriptiva'),
	(134,'Gestión Ambiental'),
	(135,'Gestión de Calidad'),
	(136,'Gestión de Calidad e Inocuidad'),
	(137,'Gestión de Costos'),
	(138,'Gestión de las Organizaciones'),
	(139,'Gestión de Proyectos de Software'),
	(140,'Herramientas Declarativas en Programación'),
	(141,'Higiene y Seguridad Industrial'),
	(142,'Identificación y Control Adaptativo'),
	(143,'Incendios y Explosiones'),
	(144,'Informática'),
	(145,'Informática, Algoritmos y Programación'),
	(146,'Ingeniería Ambiental'),
	(147,'Ingeniería de Requerimientos'),
	(148,'Ingeniería Genética I'),
	(149,'Ingeniería Genética II'),
	(150,'Inglés'),
	(151,'Inglés Básico'),
	(152,'Inglés I'),
	(153,'Inglés II'),
	(154,'Inglés Técnico'),
	(155,'Inmunología'),
	(156,'Instrumentación'),
	(157,'Instrumentos y Mediciones'),
	(158,'Introducción a  Ingeniería en Automatización y Control Industrial'),
	(159,'Introducción a la Bioinformática'),
	(160,'Introducción a la Biotecnología'),
	(161,'Introducción a la Biotecnología Animal'),
	(162,'Introducción a la Biotecnología Vegetal'),
	(163,'Introducción a la Ingeniería en Alimentos'),
	(164,'Introducción a la Náutica'),
	(165,'Introducción a la programación'),
	(166,'Introducción a la Programación'),
	(167,'Introducción a las Arquitecturas de Software'),
	(168,'Introducción al Conocimiento de la Física y la Química'),
	(169,'Introducción al Desarrollo de Videojuegos'),
	(170,'Laboratorio de Análisis Bromatológico'),
	(171,'Laboratorio de Automatización I'),
	(172,'Laboratorio de Automatización II'),
	(173,'Laboratorio de Control de Calidad'),
	(174,'Laboratorio de Microbiología'),
	(175,'Laboratorio de Química Instrumental'),
	(176,'Laboratorio de Sistemas Operativos y Redes'),
	(177,'Lectura y Escritura Académica'),
	(178,'Legislación Ambiental'),
	(179,'Lenguajes Formales y Autómatas'),
	(180,'Lógica y Programación'),
	(181,'Máquinas Industriales'),
	(182,'Matemática'),
	(183,'Matemática Aplicada'),
	(184,'Matemática Avanzada'),
	(185,'Matemática I'),
	(186,'Matemática II'),
	(187,'Matemática III'),
	(188,'Materiales'),
	(189,'Materiales compuestos'),
	(190,'Materias Primas de la Industria Petroquímica'),
	(191,'Mecánica de Fluidos'),
	(192,'Mecánica de los Fluidos Aplicada'),
	(193,'Medio Ambiente y Química Ambiental'),
	(194,'Metodología de Desarrollo de Sistemas en Hardware y Software'),
	(195,'Métodos Numéricos'),
	(196,'Microbiología Aplicada'),
	(197,'Microbiología de Alimentos'),
	(198,'Microbiología General'),
	(199,'Microbiología Industrial'),
	(200,'Modelización de Sistemas Biológicos'),
	(201,'Modelos Animales y Bioterio'),
	(202,'Nanobiotecnología '),
	(203,'Operaciones Unitarias'),
	(204,'Organización de Computadoras'),
	(205,'Organización de la Producción Naval'),
	(206,'Organización Industrial'),
	(207,'Organización y Arquitectura de Computadores'),
	(208,'Parseo y generación de código'),
	(209,'Participación y Gestión en Proyectos de Software Libre'),
	(210,'Políticas Públicas en la Sociedad de la Información y la Era Digital'),
	(211,'Práctica del Desarrollo de Software'),
	(212,'Práctica Profesional Supervisada'),
	(213,'Preservación de Alimentos'),
	(214,'Probabilidad y Estadística'),
	(215,'Problemas Actuales de Ciencia y Tecnología'),
	(216,'Procesamiento Digital de Imágenes'),
	(217,'Procesos Industriales'),
	(218,'Producción de Proteínas Recombinantes'),
	(219,'Producción por Fermentadores'),
	(220,'Programación con Objetos I'),
	(221,'Programación con Objetos II'),
	(222,'Programación con Objetos III'),
	(223,'Programación Concurrente'),
	(224,'Programación Funcional'),
	(225,'Química Analítica'),
	(226,'Química Biológica'),
	(227,'Química de los Alimentos'),
	(228,'Química General'),
	(229,'Química I'),
	(230,'Química II'),
	(231,'Química Orgánica'),
	(232,'Química Orgánica Ecocompatible'),
	(233,'Química Orgánica I'),
	(234,'Química Orgánica II'),
	(235,'Recuperación y Purificación de Proteínas'),
	(236,'Recursos Humanos'),
	(237,'Redes de Computadoras'),
	(238,'Reservorios Petroleros'),
	(239,'Riesgos I'),
	(240,'Riesgos II'),
	(241,'Salud Pública y Ambiente'),
	(242,'Seguridad de la Información'),
	(243,'Seguridad en Industrias  y Empresas'),
	(244,'Seguridad industrial'),
	(245,'Semántica de Lenguajes de Programación'),
	(246,'Seminario de Automatización y Control'),
	(247,'Seminario de Grado'),
	(248,'Seminarios'),
	(249,'Seminarios sobre Herramientas o Técnicas Puntuales'),
	(250,'Señales y Sistemas'),
	(251,'Servicios de Planta'),
	(252,'Servicios y Operaciones de Planta'),
	(253,'Sistemas de Gestión de la Salud y la Seguridad Ocupacional'),
	(254,'Sistemas de Información Geográfica'),
	(255,'Sistemas de Representación'),
	(256,'Sistemas Distribuidos'),
	(257,'Sistemas Embebidos de Aplicación Industrial'),
	(258,'Sistemas No Lineales'),
	(259,'Sistemas Operativos'),
	(260,'Sistemas Propulsivos'),
	(261,'Taller de Arquitectura Naval'),
	(262,'Taller de Dibujo y Maquetería'),
	(263,'Taller de Física Aplicada'),
	(264,'Taller de Química'),
	(265,'Taller de Trabajo Intelectual'),
	(266,'Taller de Trabajo Universitario'),
	(267,'Técnicas Analíticas Instrumentales'),
	(268,'Técnicas Analíticas Separativas'),
	(269,'Técnicas Avanzadas de Programación'),
	(270,'Técnicas Básicas de Laboratorio'),
	(271,'Técnicas de Biología Molecular y Genética'),
	(272,'Técnicas Digitales "A"'),
	(273,'Técnicas Inmunológicas'),
	(274,'Técnicas numéricas de análisis de estructuras'),
	(275,'Tecnicatura y mercado laboral'),
	(276,'Tecnología de Alimentos'),
	(277,'Teoría de Circuitos'),
	(278,'Teoría de la Computación'),
	(279,'Termodinámica'),
	(280,'Tópicos de Confiabilidad y Mantenimiento para la Industria Automatizada'),
	(281,'Tópicos de Control Avanzado'),
	(282,'Tópicos de Inteligencia Artificial'),
	(283,'Toxicología de Alimentos'),
	(284,'Trabajo de Inserción Profesional'),
	(285,'Trabajo Final'),
	(286,'Tratamiento de Efluentes'),
	(287,'Tratamiento de Efluentes Sólidos y Gaseosos'),
	(288,'Virología Aplicada'),
	(289,'Visión Artificial');
